baseURL = "/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "RainbowCake Documentation"
theme = "learn"
# themesdir = "../.."
#pygmentsCodeFences = true
#pygmentsStyle = "monokailight"

#defaultContentLanguage = "en"
#defaultContentLanguageInSubdir= false
#enableMissingTranslationPlaceholders = false


[params]
author = "Márton Braun"
disableSearch = true
disableInlineCopyToClipBoard = true
disableLanguageSwitchingButton = true
themeVariant = "blue"

[outputs]
home = [ "HTML" ]


[[menu.shortcuts]]
name = "<i class='fab fa-gitlab'></i> GitLab repo"
url = "https://gitlab.autsoft.hu/AutSoft/AndroidChapter/rainbow-cake/rainbow-cake"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-gitlab'></i> Sample apps"
url = "https://gitlab.autsoft.hu/AutSoft/AndroidChapter/rainbow-cake/demos"
weight = 11
